[program:pembayaran-queue-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/html/pembayaran
command=/usr/bin/php /var/www/html/pembayaran/artisan queue:work database --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/pembayaran/storage/logs/queue-worker.log
stopwaitsecs=3600
