[program:pembayaran-wa-gateway]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/html/pembayaran/fastapi/wa-gateway
command=/usr/bin/node /var/www/html/pembayaran/fastapi/wa-gateway/server.js
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=admin
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/pembayaran/storage/logs/wa-gateway.out
stopwaitsecs=120
