<?php

return [
    'permissions' => [
        ['key' => 'dashboard.view', 'label' => 'Lihat dashboard'],
        ['key' => 'dashboard.prediction.view', 'label' => 'Lihat dashboard prediksi'],
        ['key' => 'report.view', 'label' => 'Lihat laporan'],

        ['key' => 'billing.invoice.view', 'label' => 'Lihat billing'],
        ['key' => 'billing.invoice.create', 'label' => 'Buat invoice'],
        ['key' => 'billing.invoice.approve', 'label' => 'Konfirmasi/tolak pembayaran'],
        ['key' => 'billing.invoice.adjust', 'label' => 'Edit nominal invoice'],
        ['key' => 'billing.invoice.manage', 'label' => 'Manajemen invoice'],
        ['key' => 'billing.dunning.view', 'label' => 'Lihat dunning billing'],
        ['key' => 'billing.dunning.manage', 'label' => 'Kelola dunning billing'],
        ['key' => 'billing.payment_capture.manage', 'label' => 'Kelola payment capture'],
        ['key' => 'billing.payment_capture.review', 'label' => 'Review payment capture'],

        ['key' => 'customer.view', 'label' => 'Lihat pelanggan'],
        ['key' => 'customer.create', 'label' => 'Tambah pelanggan'],
        ['key' => 'customer.update', 'label' => 'Edit pelanggan'],
        ['key' => 'customer.delete', 'label' => 'Hapus pelanggan'],
        ['key' => 'customer.verification', 'label' => 'Verifikasi pelanggan'],
        ['key' => 'customer.package_audit.view', 'label' => 'Lihat audit kesesuaian paket pelanggan'],
        ['key' => 'customer.package_audit.manage', 'label' => 'Kelola sinkronisasi paket pelanggan'],
        ['key' => 'customer.package_migration.manage', 'label' => 'Migrasi PPPoE pelanggan'],
        ['key' => 'customer.account.manage', 'label' => 'Kelola akun login pelanggan'],
        ['key' => 'customer.wifi.manage', 'label' => 'Ubah password WiFi pelanggan'],

        ['key' => 'odp.view', 'label' => 'Lihat ODP'],
        ['key' => 'odp.manage', 'label' => 'Kelola ODP'],
        ['key' => 'odp.mapping.view', 'label' => 'Lihat pemetaan ODP'],
        ['key' => 'odp.mapping.assign', 'label' => 'Assign pemetaan ODP'],

        ['key' => 'complaint.view', 'label' => 'Lihat aduan/ticket'],
        ['key' => 'complaint.update', 'label' => 'Ubah aduan/ticket'],
        ['key' => 'complaint.report', 'label' => 'Laporan aduan/ticket'],

        ['key' => 'incident.view', 'label' => 'Lihat incident'],
        ['key' => 'incident.manage', 'label' => 'Buka/tutup incident'],
        ['key' => 'incident.run_engine', 'label' => 'Jalankan incident engine'],

        ['key' => 'installation.view', 'label' => 'Lihat workflow instalasi'],
        ['key' => 'installation.manage', 'label' => 'Kelola workflow instalasi'],

        ['key' => 'inventory.view', 'label' => 'Lihat inventori'],
        ['key' => 'inventory.manage', 'label' => 'Kelola inventori'],
        ['key' => 'inventory.master.manage', 'label' => 'Kelola master inventori'],

        ['key' => 'finance.mutation.view', 'label' => 'Lihat mutasi'],
        ['key' => 'finance.mutation.manage', 'label' => 'Kelola mutasi'],
        ['key' => 'finance.expense.manage', 'label' => 'Kelola pengeluaran'],

        ['key' => 'payroll.view', 'label' => 'Lihat payroll'],
        ['key' => 'payroll.manage', 'label' => 'Kelola payroll'],

        ['key' => 'monitoring.view', 'label' => 'Lihat monitoring'],
        ['key' => 'monitoring.maps.view', 'label' => 'Lihat monitoring maps'],
        ['key' => 'isolir.view', 'label' => 'Lihat isolir'],

        ['key' => 'masterdata.view', 'label' => 'Lihat master data'],
        ['key' => 'master.wilayah.manage', 'label' => 'Kelola master wilayah'],
        ['key' => 'master.mikrotik.manage', 'label' => 'Kelola master mikrotik'],
        ['key' => 'master.package.manage', 'label' => 'Kelola paket'],
        ['key' => 'master.promo.manage', 'label' => 'Kelola promo'],
        ['key' => 'master.payment.manage', 'label' => 'Kelola metode pembayaran'],
        ['key' => 'master.expense_category.manage', 'label' => 'Kelola master jenis pengeluaran'],
        ['key' => 'master.network_notice.manage', 'label' => 'Kelola network notice'],
        ['key' => 'master.customer_wifi_links.manage', 'label' => 'Kelola link WiFi pelanggan'],

        ['key' => 'user.manage', 'label' => 'Kelola akun pengguna'],
        ['key' => 'access_policy.manage', 'label' => 'Kelola akses & policy'],
        ['key' => 'financial_target.manage', 'label' => 'Kelola target keuangan'],
    ],

    // Baseline kompatibilitas lama.
    'baseline_roles' => [
        'superadmin' => ['*'],
        'admin' => [
            'dashboard.view',
            'dashboard.prediction.view',
            'report.view',
            'billing.invoice.view',
            'billing.invoice.create',
            'billing.invoice.approve',
            'billing.invoice.adjust',
            'billing.invoice.manage',
            'billing.dunning.view',
            'billing.dunning.manage',
            'billing.payment_capture.manage',
            'billing.payment_capture.review',
            'customer.view',
            'customer.create',
            'customer.update',
            'customer.delete',
            'customer.verification',
            'customer.package_audit.view',
            'customer.package_audit.manage',
            'customer.wifi.manage',
            'odp.view',
            'odp.manage',
            'odp.mapping.view',
            'odp.mapping.assign',
            'complaint.view',
            'complaint.update',
            'complaint.report',
            'incident.view',
            'incident.manage',
            'incident.run_engine',
            'installation.view',
            'installation.manage',
            'inventory.view',
            'inventory.manage',
            'finance.mutation.view',
            'finance.expense.manage',
            'payroll.view',
            'payroll.manage',
            'monitoring.view',
            'monitoring.maps.view',
            'isolir.view',
            'masterdata.view',
            'master.wilayah.manage',
            'master.mikrotik.manage',
            'master.package.manage',
            'master.promo.manage',
            'master.payment.manage',
            'master.expense_category.manage',
            'master.network_notice.manage',
            'master.customer_wifi_links.manage',
        ],
        'teknisi' => [
            'dashboard.view',
            'customer.view',
            'customer.create',
            'customer.update',
            'customer.delete',
            'customer.verification',
            'customer.package_audit.view',
            'customer.wifi.manage',
            'odp.view',
            'odp.manage',
            'odp.mapping.view',
            'odp.mapping.assign',
            'complaint.view',
            'complaint.update',
            'complaint.report',
            'incident.view',
            'incident.manage',
            'incident.run_engine',
            'installation.view',
            'installation.manage',
            'inventory.view',
            'inventory.manage',
            'payroll.view',
            'monitoring.view',
            'monitoring.maps.view',
            'isolir.view',
            'masterdata.view',
            'master.network_notice.manage',
        ],
        'finance' => [
            'dashboard.view',
            'dashboard.prediction.view',
            'report.view',
            'billing.invoice.view',
            'billing.invoice.create',
            'billing.invoice.approve',
            'billing.invoice.adjust',
            'billing.invoice.manage',
            'billing.dunning.view',
            'billing.dunning.manage',
            'billing.payment_capture.manage',
            'billing.payment_capture.review',
            'customer.package_audit.view',
            'finance.mutation.view',
            'finance.mutation.manage',
            'finance.expense.manage',
            'payroll.view',
            'payroll.manage',
            'inventory.view',
            'inventory.manage',
            'masterdata.view',
            'master.payment.manage',
        ],
    ],

    'menu_map' => [
        ['menu_key' => 'dashboard', 'label' => 'Dashboard', 'permission_keys' => ['dashboard.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'dashboard_prediction', 'label' => 'Prediksi', 'permission_keys' => ['dashboard.prediction.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'reports', 'label' => 'Laporan', 'permission_keys' => ['report.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'billing', 'label' => 'Penagihan', 'permission_keys' => ['billing.invoice.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'customers', 'label' => 'Pelanggan', 'permission_keys' => ['customer.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'customer_verification', 'label' => 'Verifikasi Pelanggan', 'permission_keys' => ['customer.verification'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'customer_package_management', 'label' => 'Manajemen Paket Pelanggan', 'permission_keys' => ['customer.package_audit.view'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'customer_package_migration', 'label' => 'Migrasi PPPoE Pelanggan', 'permission_keys' => ['customer.package_migration.manage'], 'navbar_section' => 'admin', 'default_visible' => true],
        ['menu_key' => 'customer_account_mapping', 'label' => 'Mapping Akun Pelanggan', 'permission_keys' => ['customer.account.manage'], 'navbar_section' => 'admin', 'default_visible' => true],
        ['menu_key' => 'odp_mapping', 'label' => 'Pemetaan ODP', 'permission_keys' => ['odp.mapping.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'inventory', 'label' => 'Inventori', 'permission_keys' => ['inventory.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'pengeluaran', 'label' => 'Pengeluaran', 'permission_keys' => ['finance.expense.manage'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'payroll', 'label' => 'Payroll', 'permission_keys' => ['payroll.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'mutasi', 'label' => 'Mutasi', 'permission_keys' => ['finance.mutation.view'], 'navbar_section' => 'main', 'default_visible' => true],
        ['menu_key' => 'monitoring', 'label' => 'Monitoring', 'permission_keys' => ['monitoring.view'], 'navbar_section' => 'operations', 'default_visible' => true],
        ['menu_key' => 'monitoring_maps', 'label' => 'Monitoring Maps', 'permission_keys' => ['monitoring.maps.view'], 'navbar_section' => 'operations', 'default_visible' => true],
        ['menu_key' => 'isolir', 'label' => 'Isolir', 'permission_keys' => ['isolir.view'], 'navbar_section' => 'operations', 'default_visible' => true],
        ['menu_key' => 'complaints', 'label' => 'Aduan Pelanggan', 'permission_keys' => ['complaint.view'], 'navbar_section' => 'operations', 'default_visible' => true],
        ['menu_key' => 'network_notices', 'label' => 'Info Gangguan', 'permission_keys' => ['master.network_notice.manage'], 'navbar_section' => 'operations', 'default_visible' => true],
        ['menu_key' => 'wa_notification', 'label' => 'Kirim Notifikasi WA', 'permission_keys' => ['master.network_notice.manage'], 'navbar_section' => 'operations', 'default_visible' => true],
        ['menu_key' => 'odp_management', 'label' => 'Kelola ODP', 'permission_keys' => ['odp.view'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'distribution_route', 'label' => 'Jalur Distribusi', 'permission_keys' => ['odp.mapping.view'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'installation', 'label' => 'Workflow Instalasi', 'permission_keys' => ['installation.view'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'master_data', 'label' => 'Master Data', 'permission_keys' => ['masterdata.view'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'master_wilayah', 'label' => 'Master Wilayah', 'permission_keys' => ['master.wilayah.manage'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'master_mikrotik', 'label' => 'Master Mikrotik', 'permission_keys' => ['master.mikrotik.manage'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'package_management', 'label' => 'Manajemen Paket', 'permission_keys' => ['master.package.manage'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'payment_methods', 'label' => 'Metode Pembayaran', 'permission_keys' => ['master.payment.manage'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'expense_categories', 'label' => 'Jenis Pengeluaran', 'permission_keys' => ['master.expense_category.manage'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'payment_receipts', 'label' => 'Receipt Pembayaran', 'permission_keys' => ['master.payment.manage'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'promo_management', 'label' => 'Promosi', 'permission_keys' => ['master.promo.manage'], 'navbar_section' => 'settings', 'default_visible' => true],
        ['menu_key' => 'user_management', 'label' => 'Kelola Akun', 'permission_keys' => ['user.manage'], 'navbar_section' => 'admin', 'default_visible' => true],
        ['menu_key' => 'invoice_management', 'label' => 'Manajemen Invoice', 'permission_keys' => ['billing.invoice.manage'], 'navbar_section' => 'admin', 'default_visible' => true],
        ['menu_key' => 'financial_targets', 'label' => 'Target Keuangan', 'permission_keys' => ['financial_target.manage'], 'navbar_section' => 'admin', 'default_visible' => true],
        ['menu_key' => 'access_policy', 'label' => 'Akses & Policy', 'permission_keys' => ['access_policy.manage'], 'navbar_section' => 'admin', 'default_visible' => true],
    ],

    'priority_modules' => [
        'billing',
        'odp_mapping',
        'complaints',
        'incidents',
        'installation',
        'master_settings',
    ],
];
